export const DEFAULT_CONFIG = {
  devMode: false,
  gameName: 'Untitled?',
  showGameName: true,
  gameNameFont: "'Great Vibes', cursive",
  gameNameSize: 32,
  cols: 17,
  rows: 10,
  shapeSize: 40,
  tileBorder: 2,
  textSize: 22,
  maxTime: 100,
  currentTime: 100,
  score: 0,
  minNum: 1,
  maxNum: 9,
  clearAnimationType: 'munching' as 'munching' | 'fadeout',
  munchSpeed: 80,
  munchDuration: 600,
  fadeoutDuration: 400,
  textColor: '#ffffff',
  textBorderColor: '#4a2e12',
  gameBg: '#fbf2df',
  checker1: '#ffddab',
  checker2: '#ffba53',
  checkerPadding: 120,
  checkerSize: 120,
  selectionColor: '#ff9f1c',
  validColor: '#10b981',
  groupingMode: 'auto-square' as 'auto-square' | 'separate',
  mouseButtonMapping: 'left-box-right-diag' as 'left-box-right-diag' | 'left-diag-right-box',
  twoClickSelection: true,
  hoverLiveSelection: true,
};

export const FONT_OPTIONS = [
  { value: "'Great Vibes', cursive", label: '✨ Great Vibes (Luxurious Cursive)' },
  { value: "'Alex Brush', cursive", label: '💎 Alex Brush (Classic Elegance)' },
  { value: "'MonteCarlo', cursive", label: '👑 MonteCarlo (Royal Cursive)' },
  { value: "'Dancing Script', cursive", label: '💃 Dancing Script (Modern Cursive)' },
  { value: "'Playfair Display', serif", label: '📜 Playfair Display (Luxury Serif)' },
  { value: "'Gluten', cursive", label: '🐱 Gluten (Playful Cat Font)' },
  { value: "'Segoe UI', sans-serif", label: 'Segoe UI' },
  { value: "'Roboto', sans-serif", label: 'Roboto' },
  { value: "'Comic Sans MS', cursive", label: 'Comic Sans MS' },
  { value: "'Courier New', monospace", label: 'Courier New' },
  { value: "'Georgia', serif", label: 'Georgia' },
  { value: "'Trebuchet MS', sans-serif", label: 'Trebuchet MS' },
  { value: "'Impact', sans-serif", label: 'Impact' },
];

export const BM_COLOR_PALETTE: Record<number, string> = {
  0: '#ffffff',
  1: '#3b82f6',
  2: '#10b981',
  3: '#ef4444',
  4: '#8b5cf6',
  5: '#f97316',
  6: '#eab308',
  7: '#ec4899',
  8: '#14b8a6',
  9: '#c96a2e',
};
